name: YAML schema validator
on: 
  push:
    branches:
      - main
    paths: 
      - "**/_*.yml"
      - "schemas/_*.schema.yml"
      - ".github/workflows/validate-yaml.yml"
      - "scripts/validate-yaml.ts"
  pull_request:
    paths: 
      - "**/_*.yml"
      - "schemas/_*.schema.yml"
      - ".github/workflows/validate-yaml.yml"
      - "scripts/validate-yaml.ts"

defaults:
  run:
    working-directory: scripts

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run --allow-net --allow-read ./validate-yaml.ts